name: ia-env
dependencies:
  - python=3.8
  - pip
  - pip:
    - matplotlib
    - numpy
    - PyQt5
    - pyqtgraph
    - pyRestTable
    - rsMap3D
    - scikit-learn
    - spec2nexus
    - tifffile
    - xrayutilities