name: ia-env
dependencies:
  - python=3.7
  - numpy=1.20.*
  - pip
  - pip:
    - coverage
    - PyQt5==5.15.4
    - pyqtgraph==0.12.1
    - pytest
    - pytest-qt
    - spec2nexus
    - xrayutilities