name: ia-env
dependencies:
  - python=3.7
  - numpy=1.20.*
  - pip
  - pip:
    - coverage
    - matplotlib
    - PyQt5==5.15.4
    - pyqtgraph==0.12.1
    - pytest
    - pytest-qt
    - rsMap3D
    - spec2nexus
    - tifffile
    - xrayutilities