name: ia-env
dependencies:
  - python=3.8
  - pip
  - pip:
    - matplotlib==3.5.3
    - numpy==1.23.1
    - PyQt5==5.15.7
    - pyqtgraph==0.12.1
    - pyRestTable==2020.0.3
    - rsMap3D==1.2.1
    - scikit-learn==1.1.2
    - spec2nexus==2021.1.3
    - tifffile==2022.8.8
    - xrayutilities==1.7.3